# Generated by Django 5.0 on 2024-01-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_cart_user_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pwd_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
